### ISSUE TITLE
Missing dependency when pip installing

### ISSUE THREAD

**Issue by travisemslander** [boto/s3transfer#202]
We use s3transfer as a dependency of the awscli package. Recently aws cli stopped working and upon investigation we found that awscli released version 1.20.0 which used s3transfer 0.5.0. Previously it was using the 0.4.x version and s3transfer would cause futures to be installed. With the 0.5.0 version we are no longer seeing the futures package installed, and then upon running awscli we see:

```Traceback (most recent call last):
  File "/usr/local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 69, in main
    driver = create_clidriver()
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 79, in create_clidriver
    event_hooks=session.get_component('event_emitter'))
  File "/usr/local/lib/python2.7/dist-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/usr/local/lib/python2.7/dist-packages/awscli/plugin.py", line 61, in _import_plugins
    module = __import__(path, fromlist=[module])
  File "/usr/local/lib/python2.7/dist-packages/awscli/handlers.py", line 27, in <module>
    from awscli.customizations.cloudformation import initialize as cloudformation_init
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/cloudformation/__init__.py", line 13, in <module>
    from awscli.customizations.cloudformation.package import PackageCommand
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/cloudformation/package.py", line 26, in <module>
    from awscli.customizations.s3uploader import S3Uploader
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/s3uploader.py", line 22, in <module>
    from s3transfer.manager import TransferManager
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/__init__.py", line 134, in <module>
    import concurrent.futures
ImportError: No module named concurrent.futures
```

We can work around this by locking to the older awscli or installing futures ourselves, but it seems the s3transfer package really should be identifying it requires futures or you'll have a lot of people hitting this issue. Especially when this package is being installed in build pipelines it can cause major headaches.

**Comment by travisemslander** [comment]
Upon investigation to see if I could provide a potential fix I'm noticing this appears to be intentional as support for python 2.7 was removed and that was the case when the futures package was used. I'll close this issue report.
