### ISSUE TITLE
Test error - ERROR: setUpClass (tests.integration.test_s3transfer.TestS3Transfers)

### ISSUE THREAD

**Issue by Fale** [boto/s3transfer#8]
Running the tests on F24 (next Fedora release), this is what I get:
```

ERROR: setUpClass (tests.integration.test_s3transfer.TestS3Transfers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/s3transfer-0.0.1/tests/integration/test_s3transfer.py", line 118, in setUpClass
    CreateBucketConfiguration={'LocationConstraint': cls.region})
  File "/usr/lib/python3.5/site-packages/botocore/client.py", line 301, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.5/site-packages/botocore/client.py", line 387, in _make_api_call
    operation_model, request_dict)
  File "/usr/lib/python3.5/site-packages/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python3.5/site-packages/botocore/endpoint.py", line 136, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/lib/python3.5/site-packages/botocore/endpoint.py", line 120, in create_request
    operation_name=operation_model.name)
  File "/usr/lib/python3.5/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python3.5/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python3.5/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/lib/python3.5/site-packages/botocore/signers.py", line 123, in sign
    signature_version)
  File "/usr/lib/python3.5/site-packages/botocore/signers.py", line 153, in get_auth_instance
    kwargs['credentials'] = self._credentials.get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
```

[Full build log](https://copr-be.cloud.fedoraproject.org/results/fale/aws-latest/fedora-rawhide-x86_64/00162341-python-s3transfer/build.log.gz)
[Environment creation](https://copr-be.cloud.fedoraproject.org/results/fale/aws-latest/fedora-rawhide-x86_64/00162341-python-s3transfer/root.log.gz)

**Comment by kyleknap** [comment]
@Fale 
This looks like you are running into the same issue as this one: https://github.com/boto/boto3/issues/498. From the sound of the issue, you may not be setting your credentials correctly. Let me know if this helps you run the tests. We are working to improve the error message as well.

**Comment by Fale** [comment]
Thanks a lot for the response.
I'm pretty shocked by the fact that to run tests I need to put credentials in it (and I'll not be able to do so, otherwise the whole world will see them).
Is there an option to run only offline tests? Is there a plan to have only offline tests?

**Comment by kyleknap** [comment]
You only need credentials to run the integration tests. For all most of the projects that we maintain: botocore, boto3, AWS CLI, if a test is in the integration directory then you will most likely need credentials because it will make a request over the wire to the AWS service.

Our offline tests that is comparable to the integration test suite it is the functional test suite. It is pretty much an integration test except we do not send the request over the wire at the very end and we return our own response. These tests do not require credentials for them to pass. For your use case, I would recommend just running the tests in the ``unit`` and ``functional`` test suites to make sure everything is working. That is the same thing we do for our Travis job for this GitHub repository. For Travis, we just run this script for the tests: https://github.com/boto/s3transfer/blob/develop/scripts/ci/run-tests. Let us know if that helps.

**Comment by Fale** [comment]
Thanks a lot :) I'll implement what you suggested!
